### PR TITLE
Moddable camera positions for custom characters

### PR DESCRIPTION
**Pull request by dylanisreal**

### CODE REVIEW

**Review by thepercentageguy — CHANGES_REQUESTED** [review]
Cache the character instead of reloading it every time, also make the character actually visible.

**Review by thepercentageguy — APPROVED** [review]

**Review by thepercentageguy — CHANGES_REQUESTED** [review]
how about still including the cam pos variables as an example

**Review by thepercentageguy — APPROVED** [review]
hi, my name is dumb

**Review by SpunBlue — CHANGES_REQUESTED** [review]
Tested the Custom Camera Positions for the Example Char, Immediately crashed the test song, There's definitely something broken.

**Comment by thepercentageguy** [comment]
Closed due to no fix.

**Pull request closed without merging**
